name = "get-to-learning"
main = "src/index.ts"
compatibility_date = "2025-01-15"

routes = [
  { pattern = "gtl.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "gtl-db"
database_id = "d740952f-4fd9-4a0b-b85f-2ffd042fffd3"

[dev]
port = 8787
